import { describe, it } from "node:test";
import assert from "node:assert/strict";

// The built artifact (regenerated by `node scripts/build.js`, which the `test`
// script runs first).
import previewsByCollection from "../index.json" with { type: "json" };

describe("index.json", () => {
  it("is a non-empty object keyed by collection NSID", () => {
    const collections = Object.keys(previewsByCollection);
    assert.ok(collections.length > 0);
    for (const collection of collections) {
      assert.ok(collection.includes("."), `not an NSID: ${collection}`);
    }
  });

  it("maps each collection to a non-empty template string", () => {
    for (const [collection, template] of Object.entries(previewsByCollection)) {
      assert.equal(typeof template, "string", `${collection} template not a string`);
      assert.ok(template.length > 0, `${collection} template empty`);
      assert.ok(template.includes("{"), `${collection} template has no placeholder`);
    }
  });

  it("previews a known collection", () => {
    assert.equal(previewsByCollection["app.bsky.feed.post"], "{value.text}");
  });
});
